# Heroku Best Practices For Eureka Client:
# https://github.com/kissaten/heroku-eureka-client-demo

server.port: ${PORT:8082}

eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    non-secure-port: 80
  client:
    fetchRegistry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/


# TO run this set SPRING_PROFILES_ACTIVE to cloud in Run Configuration
---
spring.profiles: cloud

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver


---
spring.profiles: local, default

# this should go in the LOCAL profile
# Should access at: http://localhost:8082/h2/
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

