server.port: 8082
spring.application.name: bug-wars-ai-crud

# TO run this set SPRING_PROFILES_ACTIVE to cloud in Run Configuration
---
spring.profiles: cloud
eureka:
  password: password
  instance:
    hostname: bug-wars-eureka.herokuapp.com
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@${eureka.instance.hostname}/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver


---
spring.profiles: local, default
eureka:
  password: password
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@${eureka.instance.hostname}:8761/eureka/


# this should go in the LOCAL profile
# Should access at: http://localhost:8082/h2/
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

