server.port: 8082
spring.application.name: bug-wars-ai-crud


# this should go in the LOCAL profile
# Should access at: http://localhost:8082/h2-console/

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

---
spring.profiles: local, default
eureka:
  password: password
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@${eureka.instance.hostname}:8761/eureka/
