# Heroku Best Practices For Eureka Client:
# https://github.com/kissaten/heroku-eureka-client-demo

server.port: ${PORT:8082}

# TO run this set SPRING_PROFILES_ACTIVE to cloud in Run Configuration
---
spring.profiles: cloud
eureka:
  password: password
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  client:
    fetchRegistry: true
    register-with-eureka: true
    healthcheck.enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:8761}/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver


---
spring.profiles: local, default
eureka:
  password: password
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@${eureka.instance.hostname}:8761/eureka/


# this should go in the LOCAL profile
# Should access at: http://localhost:8082/h2/
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

