server.port: 8082
spring.application.name: bug-wars-ai-crud



---
spring.profiles: cloud, default
eureka:
  password: password
  instance:
    hostname: bug-wars-eureka.herokuapp.com
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@${eureka.instance.hostname}/eureka

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
#    url: ${DATABASE_URL}
    url: jdbc:postgresql://ec2-54-160-202-3.compute-1.amazonaws.com:5432/d9155cq2c6gmil?user=lqzrumgmygdscy&password=a647fb09669b6c1c8d0ceca677e2391d8f1fe80e60c6e2c551f2ba51a8fda16d
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver


# TO run this set SPRING_PROFILES_ACTIVE to local in Run Configuration
---
spring.profiles: local
eureka:
  password: password
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://user:${eureka.password}@${eureka.instance.hostname}:8761/eureka/


# this should go in the LOCAL profile
# Should access at: http://localhost:8082/h2-console/
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

