server.port: 8082

# this should go in the LOCAL profile
# Should access at: http://localhost:8082/h2-console/

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver