name: Deploy AI CRUD
# Trigger the workflow when there is a push to main
on:
  push:
    branches: [ main ]
# What to do when triggered
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
        #Build and run test fro Spring Boot
      - name: Build Sprint Boot Project with Maven
        run: mvn -B package --file pom.xml
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bug-wars-ai-crud"
          heroku_email: "jerry.codecamp@gmail.com"
          justlogin: true
      - name: Deploy to Heroku
        run: |
          heroku plugins:install java
          heroku deploy:jar target/bug-wars-ai-crud-0.0.1-SNAPSHOT.jar --app bug-wars-ai-crud